/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FaqEntry { 'question' : string, 'answer' : string }
export interface FaqSuggestion {
  'createdAt' : Time,
  'sourceContent' : string,
  'sourceAuthor' : Principal,
  'suggestedQuestion' : string,
  'sourceMessageId' : MessageId,
}
export interface MamaFeedbackMetadata {
  'explanation' : string,
  'userPrompt' : string,
  'category' : string,
}
export interface Message {
  'id' : MessageId,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'isPublic' : boolean,
}
export type MessageId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFaqEntry' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateVarietySeed' : ActorMethod<[], [bigint, boolean]>,
  'clearFeedbackMetadata' : ActorMethod<[], undefined>,
  'findFaqMatch' : ActorMethod<[string], [] | [FaqEntry]>,
  'getAllCategoryStats' : ActorMethod<[], Array<[string, number, bigint]>>,
  'getAllCategoryTotalsByUser' : ActorMethod<[], Array<[string, number]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryStats' : ActorMethod<
    [string],
    [] | [
      {
        'count' : bigint,
        'recentTimestamps' : Array<Time>,
        'averageScore' : number,
      }
    ]
  >,
  'getChatStats' : ActorMethod<[], [bigint, bigint, bigint]>,
  'getFeedbackMetadata' : ActorMethod<[], [] | [MamaFeedbackMetadata]>,
  'getNewPublicMessages' : ActorMethod<[], Array<Message>>,
  'getPendingFaqSuggestions' : ActorMethod<[], Array<FaqSuggestion>>,
  'getPersonalizedVarietySeed' : ActorMethod<[], [] | [bigint]>,
  'getPrivateMessages' : ActorMethod<[], Array<Message>>,
  'getPublicMessages' : ActorMethod<[], Array<Message>>,
  'getPubliclyAccessibleStats' : ActorMethod<
    [],
    {
      'totalPublicMessages' : bigint,
      'totalFaqEntries' : bigint,
      'totalPrivateMessages' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVarietySeedWithFallback' : ActorMethod<[], bigint>,
  'hasPersonalizedVarietySeed' : ActorMethod<[], boolean>,
  'ignoreFaqSuggestion' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteFaqSuggestion' : ActorMethod<[string, string], undefined>,
  'resetPersonalizedVarietySeed' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFeedbackMetadata' : ActorMethod<[MamaFeedbackMetadata], undefined>,
  'searchFaqsByKeyword' : ActorMethod<[string], Array<FaqEntry>>,
  'sendMessage' : ActorMethod<[string, boolean], MessageId>,
  'setPersonalizedVarietySeed' : ActorMethod<[bigint], undefined>,
  'storeAnonymizedSignal' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];