/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FaqEntry = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const MamaFeedbackMetadata = IDL.Record({
  'explanation' : IDL.Text,
  'userPrompt' : IDL.Text,
  'category' : IDL.Text,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'isPublic' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFaqEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearFeedbackMetadata' : IDL.Func([], [], []),
  'findFaqMatch' : IDL.Func([IDL.Text], [IDL.Opt(FaqEntry)], ['query']),
  'getAllCategoryStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Nat))],
      ['query'],
    ),
  'getAllCategoryTotalsByUser' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'count' : IDL.Nat,
            'recentTimestamps' : IDL.Vec(Time),
            'averageScore' : IDL.Float64,
          })
        ),
      ],
      ['query'],
    ),
  'getChatStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
  'getFeedbackMetadata' : IDL.Func(
      [],
      [IDL.Opt(MamaFeedbackMetadata)],
      ['query'],
    ),
  'getNewPublicMessages' : IDL.Func([], [IDL.Vec(Message)], []),
  'getPppOptIn' : IDL.Func([], [IDL.Bool], ['query']),
  'getPrivateMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getPublicMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFeedbackMetadata' : IDL.Func([MamaFeedbackMetadata], [], []),
  'searchFaqsByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(FaqEntry)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setPppOptIn' : IDL.Func([IDL.Bool], [], []),
  'storeAnonymizedSignal' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FaqEntry = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const MamaFeedbackMetadata = IDL.Record({
    'explanation' : IDL.Text,
    'userPrompt' : IDL.Text,
    'category' : IDL.Text,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'isPublic' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFaqEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearFeedbackMetadata' : IDL.Func([], [], []),
    'findFaqMatch' : IDL.Func([IDL.Text], [IDL.Opt(FaqEntry)], ['query']),
    'getAllCategoryStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Nat))],
        ['query'],
      ),
    'getAllCategoryTotalsByUser' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'count' : IDL.Nat,
              'recentTimestamps' : IDL.Vec(Time),
              'averageScore' : IDL.Float64,
            })
          ),
        ],
        ['query'],
      ),
    'getChatStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
    'getFeedbackMetadata' : IDL.Func(
        [],
        [IDL.Opt(MamaFeedbackMetadata)],
        ['query'],
      ),
    'getNewPublicMessages' : IDL.Func([], [IDL.Vec(Message)], []),
    'getPppOptIn' : IDL.Func([], [IDL.Bool], ['query']),
    'getPrivateMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getPublicMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFeedbackMetadata' : IDL.Func([MamaFeedbackMetadata], [], []),
    'searchFaqsByKeyword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FaqEntry)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setPppOptIn' : IDL.Func([IDL.Bool], [], []),
    'storeAnonymizedSignal' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };